services:
  postgres:
    image: postgres:14.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: playground
    container_name: 'postgresql-container'
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data # том для того, чтобы при перезапуске контейнера все данные сохранялись
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql # начальная схема БД
    ports:
      - 5432:5432